			{"paxoms" 
				{title "PAXOM4bl"}
				{armies "pax"}
				{icon "/interface/pages/multi/flag_pax"}
			}
			{"ukrains"
				{title "PeIITNLoNDbI N3 95 KBapTaLa"}
				{armies "ukr"}
				{icon "/interface/pages/multi/flag_ukr"}
			}
			{"robots" 
				{title "KIBER TELEPUZIKI"}
				{armies "rob"}
				{icon "/interface/pages/multi/flag_rob"}
			}
			{"fembois"
				{title "4BK Femboi4ic"}
				{armies "fem"}
				{icon "/interface/pages/multi/flag_fem"}
			}
			{"tractors"
				{title "LYKAIIIENIA"}
				{armies "tra"}
				{icon "/interface/pages/multi/flag_tra"}
			}