			{"paxoms" 
				{title "/interface/pages/multi/flag_pax"}
				{armies "pax"}
				{icon "/interface/pages/multi/flag_pax"}
			}
			{"ukrains"
				{title "/interface/pages/multi/flag_ukr"}
				{armies "ukr"}
				{icon "/interface/pages/multi/flag_ukr"}
			}
			{"robots" 
				{title "/interface/pages/multi/flag_rob"}
				{armies "rob"}
				{icon "/interface/pages/multi/flag_rob"}
			}
			{"tractors"
				{title "/interface/pages/multi/flag_tra"}
				{armies "tra"}
				{icon "/interface/pages/multi/flag_tra"}
			}