MaxSquadSize = 5
OrderRotationPeriod = 3 * 60 * 1000 -- 3min (ms)
FlagPriority = { Captured = 1, Enemy = 2, Neutral = 3 }
UnitClass = {
	Infantry = "infantry",
	ATInfantry = "at-infantry",
	Vehicle = "vehicle",
	Tank = "tank",
	AATank = "aa-tank",
	ATTank = "at-tank",
	HeavyTank = "heavy-tank",
	ArtilleryTank = "artillery-tank",
}
Purchases = {
	{--purchase 1
		Repeat = 1,
		Units = {
			["eng"] = {--Commonwealth
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(eng)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(eng)"},
				{priority = 0.5, class = UnitClass.Vehicle, unit = "dodgewc55"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "willysmb_eng"}
			},
			["ger"] = {--Germany
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger)"},
				{priority = 0.5, class = UnitClass.Vehicle, unit = "r12"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "kubel_mgun"}
			},
			["ger2"] = {--Ostfront Veteranen
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger2)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger2)"},
				{priority = 0.5, class = UnitClass.Vehicle, unit = "r12_ger2"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "kfz15_gun"}
			},
			["usa"] = {--USA
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(usa)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(usa)"},
				{priority = 0.5, class = UnitClass.Vehicle, unit = "willysat"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "willysmb"}
			},
			["rus"] = {--Soviet Union
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(rus)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(rus)"},
				{priority = 0.5, class = UnitClass.Vehicle, unit = "m72"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "gaz67b"}
			},
			["jap"] = {--Japan
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(jap)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(jap)"},
				{priority = 0.5, class = UnitClass.Vehicle, unit = "type97"},
				{priority = 1.0, class = UnitClass.Tank, unit = "ha-go"}
			},
			["tra"] = {--Tractor
				{priority = 3.0, class = UnitClass.Vehicle, unit = "universal"}
			},
			["rob"] = {--Roboti
			{priority = 1.5, class = UnitClass.Infantry, unit = "homs400(rob)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "home_guard(rob)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "homs(rob)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "willysat"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m20"}
			},
			["ukr"] = {--Ukraresh
			{priority = 0.5, class = UnitClass.Infantry, unit = "zelyn(ukr)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "macarons(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "shews(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "obors(ukr)"},
			{priority = 1.1, class = UnitClass.Infantry, unit = "banderas(ukr)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "r12"},
			{priority = 0.5, class = UnitClass.Tank, unit = "sdkfz251_1"},
			{priority = 0.5, class = UnitClass.Tank, unit = "pz1b"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz2l"},
			{priority = 0.9, class = UnitClass.Tank, unit = "pz3_ukr"},
			{priority = 1.0, class = UnitClass.Tank, unit = "is2"}
			},
			["pax"] = {--Paxom
			{priority = 0.5, class = UnitClass.Infantry, unit = "paxoms(pax)"},
			{priority = 1.3, class = UnitClass.Infantry, unit = "tesass(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "malkovs(pax)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "pods(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "kats(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "babkas(pax)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "m72"},
			{priority = 0.5, class = UnitClass.Tank, unit = "m3"},
			{priority = 0.5, class = UnitClass.Tank, unit = "t20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234"},
			{priority = 0.9, class = UnitClass.Tank, unit = "t26"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3_pax"}
			}
		}
	},
	{--purchase 2
		Repeat = 1,
		Units = {
			["eng"] = {--Commonwealth
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(eng)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(eng)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "at_rifles(eng)"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk7"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "m3_eng"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "mk2daimler"}
			},
			["ger"] = {--Germany
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(ger)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "at_rifles(ger)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "sdkfz223"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "sdkfz251_1"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "sdkfz222"}
			},
			["ger2"] = {--Ostfront Veteranen
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger2)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(ger2)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "at_rifles(ger2)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "pz1b_ger2"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "sdkfz250_1"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "pz1_ger2"}
			},
			["usa"] = {--USA
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(usa)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "shotguns(usa)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "m20"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "m3_usa"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "m8grayhound"}
			},
			["rus"] = {--Soviet Union
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(rus)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(rus)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "at_rifles(rus)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "ba64"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "m3"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "ba11"}
			},
			["jap"] = {--Japan
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(jap)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(jap)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "at_rifles(jap)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "type93scout"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "ho-ha3mgun"},
				{priority = 1.0, class = UnitClass.Tank, unit = "ha-go"}
			},
			["tra"] = {--Tractor
				{priority = 3.0, class = UnitClass.Vehicle, unit = "universal"}
			},
			["rob"] = {--Roboti
			{priority = 1.0, class = UnitClass.Infantry, unit = "homs400(rob)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "home_guard(rob)"},
			{priority = 1.5, class = UnitClass.Infantry, unit = "homs(rob)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "willysat"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m8"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3"}
			},
			["ukr"] = {--Ukraresh
			{priority = 0.5, class = UnitClass.Infantry, unit = "zelyn(ukr)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "macarons(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "shews(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "obors(ukr)"},
			{priority = 1.1, class = UnitClass.Infantry, unit = "banderas(ukr)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "r12"},
			{priority = 0.5, class = UnitClass.Tank, unit = "sdkfz251_1"},
			{priority = 0.5, class = UnitClass.Tank, unit = "pz1b"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz2l"},
			{priority = 0.9, class = UnitClass.Tank, unit = "pz3_ukr"},
			{priority = 1.0, class = UnitClass.Tank, unit = "is2"}
			},
			["pax"] = {--Paxom
			{priority = 0.5, class = UnitClass.Infantry, unit = "paxoms(pax)"},
			{priority = 1.3, class = UnitClass.Infantry, unit = "tesass(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "malkovs(pax)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "pods(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "kats(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "babkas(pax)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "m72"},
			{priority = 0.5, class = UnitClass.Tank, unit = "m3"},
			{priority = 0.5, class = UnitClass.Tank, unit = "t20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234"},
			{priority = 0.9, class = UnitClass.Tank, unit = "t26"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3_pax"}
			}
		}
	},
	{--purchase 3
		Repeat = 1,
		Units = {
			["eng"] = {--Commonwealth
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(eng)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(eng)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "at_rifles(eng)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(eng)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "mk2daimler"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk3"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk6"}
			},
			["ger"] = {--Germany
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(ger)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "at_rifles(ger)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(ger)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "sdkfz222"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz2l"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "sdkfz234"}
			},
			["ger2"] = {--Ostfront Veteranen
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger2)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(ger2)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "at_rifles(ger2)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(ger2)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "pz1_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234_1"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "sdkfz234_ger2"}
			},
			["usa"] = {--USA
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(usa)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "shotguns(usa)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(usa)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "m8grayhound"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m5a1"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m24"}
			},
			["rus"] = {--Soviet Union
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(rus)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(rus)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "at_rifles(rus)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(rus)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "ba11"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t70"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_0"}
			},
			["jap"] = {--Japan
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(jap)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(jap)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "at_rifles(jap)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(jap)"},
				{priority = 1.0, class = UnitClass.Tank, unit = "ha-go"},
				{priority = 1.0, class = UnitClass.Tank, unit = "ke-nu"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-ha57"}
			},
			["tra"] = {--Tractor
				{priority = 3.0, class = UnitClass.Vehicle, unit = "universal"}
			},
			["rob"] = {--Roboti
			{priority = 1.0, class = UnitClass.Infantry, unit = "homs400(rob)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "home_guard(rob)"},
			{priority = 1.5, class = UnitClass.Infantry, unit = "homs(rob)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "willysat"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m8"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3"}
			},
			["ukr"] = {--Ukraresh
			{priority = 0.5, class = UnitClass.Infantry, unit = "zelyn(ukr)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "macarons(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "shews(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "obors(ukr)"},
			{priority = 1.1, class = UnitClass.Infantry, unit = "banderas(ukr)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "r12"},
			{priority = 0.5, class = UnitClass.Tank, unit = "sdkfz251_1"},
			{priority = 0.5, class = UnitClass.Tank, unit = "pz1b"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz2l"},
			{priority = 0.9, class = UnitClass.Tank, unit = "pz3_ukr"},
			{priority = 1.0, class = UnitClass.Tank, unit = "is2"}
			},
			["pax"] = {--Paxom
			{priority = 0.5, class = UnitClass.Infantry, unit = "paxoms(pax)"},
			{priority = 1.3, class = UnitClass.Infantry, unit = "tesass(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "malkovs(pax)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "pods(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "kats(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "babkas(pax)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "m72"},
			{priority = 0.5, class = UnitClass.Tank, unit = "m3"},
			{priority = 0.5, class = UnitClass.Tank, unit = "t20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234"},
			{priority = 0.9, class = UnitClass.Tank, unit = "t26"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3_pax"}
			}
		}
	},
	{--purchase 4
		Repeat = 1,
		Units = {
			["eng"] = {--Commonwealth
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(eng)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_eng"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(eng)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(eng)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "crusaderaa2"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "mk2daimler"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk3"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk6"},
				{priority = 1.0, class = UnitClass.Tank, unit = "cromwell_mk_vii"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk2a"}
			},
			["ger"] = {--Germany
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_ger"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(ger)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(ger)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "welberwind"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "sdkfz222"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz2l"},
				{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3n"}
			},
			["ger2"] = {--Ostfront Veteranen
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger2)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_ost"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(ger2)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(ger2)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "sdkfz7_2"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "pz1_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234_1"},
				{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3f_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3_ger2"}
			},
			["usa"] = {--USA
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(usa)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_usa"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(usa)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(usa)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "m16"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "m8grayhound"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m5a1"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m24"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m18"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m8"}
			},
			["rus"] = {--Soviet Union
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(rus)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_rus"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(rus)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(rus)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "t60"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "ba11"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t70"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_0"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "bt7a"}
			},
			["jap"] = {--Japan
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(jap)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_jap"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(jap)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(jap)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "isuzutx40_aa"},
				{priority = 1.0, class = UnitClass.Tank, unit = "ha-go"},
				{priority = 1.0, class = UnitClass.Tank, unit = "ke-nu"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-ha57"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-ha47"},
				{priority = 1.0, class = UnitClass.Tank, unit = "ho-i"}
			},
			["tra"] = {--Tractor
				{priority = 3.0, class = UnitClass.Vehicle, unit = "universal"}
			},
			["rob"] = {--Roboti
			{priority = 1.0, class = UnitClass.Infantry, unit = "homs400(rob)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "home_guard(rob)"},
			{priority = 1.5, class = UnitClass.Infantry, unit = "homs(rob)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "willysat"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m8"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3"}
			},
			["ukr"] = {--Ukraresh
			{priority = 0.5, class = UnitClass.Infantry, unit = "zelyn(ukr)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "macarons(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "shews(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "obors(ukr)"},
			{priority = 1.1, class = UnitClass.Infantry, unit = "banderas(ukr)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "r12"},
			{priority = 0.5, class = UnitClass.Tank, unit = "sdkfz251_1"},
			{priority = 0.5, class = UnitClass.Tank, unit = "pz1b"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz2l"},
			{priority = 0.9, class = UnitClass.Tank, unit = "pz3_ukr"},
			{priority = 1.0, class = UnitClass.Tank, unit = "is2"}
			},
			["pax"] = {--Paxom
			{priority = 0.5, class = UnitClass.Infantry, unit = "paxoms(pax)"},
			{priority = 1.3, class = UnitClass.Infantry, unit = "tesass(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "malkovs(pax)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "pods(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "kats(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "babkas(pax)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "m72"},
			{priority = 0.5, class = UnitClass.Tank, unit = "m3"},
			{priority = 0.5, class = UnitClass.Tank, unit = "t20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234"},
			{priority = 0.9, class = UnitClass.Tank, unit = "t26"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3_pax"}
			}
		}
	},
	{--purchase 5
		Repeat = 1,
		Units = {
			["eng"] = {--Commonwealth
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(eng)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_eng"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(eng)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(eng)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(eng)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "mk2daimler"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk3"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk6"},
				{priority = 1.0, class = UnitClass.Tank, unit = "cromwell_mk_vii"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk2a"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m4a4"},
				{priority = 1.0, class = UnitClass.Tank, unit = "cometa34"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "archer"}
			},
			["ger"] = {--Germany
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_ger"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(ger)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(ger)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(ger)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "sdkfz222"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz2l"},
				{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3n"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz4g"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz4h"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "stug3g"}
			},
			["ger2"] = {--Ostfront Veteranen
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger2)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_ost"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(ger2)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(ger2)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(ger2)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "pz1_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234_1"},
				{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3f_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz4g_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz4h_ger2"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "hetzer_ger2"}
			},
			["usa"] = {--USA
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(usa)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_usa"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(usa)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(usa)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(usa)"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "m8grayhound"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m5a1"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m24"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m18"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m8"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m4a3_75"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m4a3e8"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "m10wolverine"}
			},
			["rus"] = {--Soviet Union
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(rus)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_rus"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(rus)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(rus)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(rus)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "t60"},
				{priority = 1.0, class = UnitClass.Vehicle, unit = "ba11"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t70"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_0"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "bt7a"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_1"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_3"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "su76"}
			},
			["jap"] = {--Japan
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(jap)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_jap"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(jap)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(jap)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(jap)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "isuzutx40_aa"},
				{priority = 1.0, class = UnitClass.Tank, unit = "ha-go"},
				{priority = 1.0, class = UnitClass.Tank, unit = "ke-nu"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-ha57"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-ha47"},
				{priority = 1.0, class = UnitClass.Tank, unit = "ho-i"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-he"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-nu"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "ho-ni1"}
			},
			["tra"] = {--Tractor
				{priority = 3.0, class = UnitClass.Vehicle, unit = "universal"}
			},
			["rob"] = {--Roboti
			{priority = 1.0, class = UnitClass.Infantry, unit = "homs400(rob)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "home_guard(rob)"},
			{priority = 1.5, class = UnitClass.Infantry, unit = "homs(rob)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "willysat"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m8"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3"}
			},
			["ukr"] = {--Ukraresh
			{priority = 0.5, class = UnitClass.Infantry, unit = "zelyn(ukr)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "macarons(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "shews(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "obors(ukr)"},
			{priority = 1.1, class = UnitClass.Infantry, unit = "banderas(ukr)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "r12"},
			{priority = 0.5, class = UnitClass.Tank, unit = "sdkfz251_1"},
			{priority = 0.5, class = UnitClass.Tank, unit = "pz1b"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz2l"},
			{priority = 0.9, class = UnitClass.Tank, unit = "pz3_ukr"},
			{priority = 1.0, class = UnitClass.Tank, unit = "is2"}
			},
			["pax"] = {--Paxom
			{priority = 0.5, class = UnitClass.Infantry, unit = "paxoms(pax)"},
			{priority = 1.3, class = UnitClass.Infantry, unit = "tesass(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "malkovs(pax)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "pods(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "kats(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "babkas(pax)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "m72"},
			{priority = 0.5, class = UnitClass.Tank, unit = "m3"},
			{priority = 0.5, class = UnitClass.Tank, unit = "t20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234"},
			{priority = 0.9, class = UnitClass.Tank, unit = "t26"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3_pax"}
			}
		}
	},
	{--purchase 6
		Repeat = 1,
		Units = {
			["eng"] = {--Commonwealth
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(eng)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_eng"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(eng)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(eng)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(eng)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "crusaderaa1"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk3"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk6"},
				{priority = 1.0, class = UnitClass.Tank, unit = "cromwell_mk_vii"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk2a"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m4a4"},
				{priority = 1.0, class = UnitClass.Tank, unit = "cometa34"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "archer"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "achilles"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "m4a4_firefly"},
				{priority = 0.5, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "bishop"}
			},
			["ger"] = {--Germany
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_ger"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(ger)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(ger)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(ger)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "ostwind"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz2l"},
				{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3n"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz4g"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz4h"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "stug3g"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "jagdpanzer_iv"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "pz6e"},
				{priority = 0.5, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "wespe"}
			},
			["ger2"] = {--Ostfront Veteranen
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger2)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_ost"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(ger2)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(ger2)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(ger2)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "ostwind_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234_1"},
				{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3f_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz4g_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz4h_ger2"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "hetzer_ger2"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "nashorn_ger2"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "pz6e_ger2"},
				{priority = 0.5, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "wespe_ger2"}
			},
			["usa"] = {--USA
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(usa)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_usa"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(usa)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(usa)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(usa)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "m19"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m5a1"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m24"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m18"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m8"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m4a3_75"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m4a3e8"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "m10wolverine"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "m36"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "m4a3e2_jumbo"},
				{priority = 0.5, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "m7"}
			},
			["rus"] = {--Soviet Union
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(rus)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_rus"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(rus)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(rus)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(rus)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "zsu37"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t70"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_0"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "bt7a"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_1"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_3"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "su76"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "su85"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "kv85"},
				{priority = 0.5, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "su122"}
			},
			["jap"] = {--Japan
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(jap)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_jap"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(jap)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(jap)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(jap)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "isuzutx40_aa"},
				{priority = 1.0, class = UnitClass.Tank, unit = "ke-nu"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-ha57"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-ha47"},
				{priority = 1.0, class = UnitClass.Tank, unit = "ho-i"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-he"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-nu"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "ho-ni1"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "ho-ri"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "chi-to"},
				{priority = 0.5, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "ho-ni2"}
			},
			["tra"] = {--Tractor
				{priority = 3.0, class = UnitClass.Vehicle, unit = "universal"}
			},
			["rob"] = {--Roboti
			{priority = 1.0, class = UnitClass.Infantry, unit = "homs400(rob)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "home_guard(rob)"},
			{priority = 1.5, class = UnitClass.Infantry, unit = "homs(rob)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "willysat"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m8"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3"}
			},
			["ukr"] = {--Ukraresh
			{priority = 0.5, class = UnitClass.Infantry, unit = "zelyn(ukr)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "macarons(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "shews(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "obors(ukr)"},
			{priority = 1.1, class = UnitClass.Infantry, unit = "banderas(ukr)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "r12"},
			{priority = 0.5, class = UnitClass.Tank, unit = "sdkfz251_1"},
			{priority = 0.5, class = UnitClass.Tank, unit = "pz1b"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz2l"},
			{priority = 0.9, class = UnitClass.Tank, unit = "pz3_ukr"},
			{priority = 1.0, class = UnitClass.Tank, unit = "is2"}
			},
			["pax"] = {--Paxom
			{priority = 0.5, class = UnitClass.Infantry, unit = "paxoms(pax)"},
			{priority = 1.3, class = UnitClass.Infantry, unit = "tesass(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "malkovs(pax)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "pods(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "kats(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "babkas(pax)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "m72"},
			{priority = 0.5, class = UnitClass.Tank, unit = "m3"},
			{priority = 0.5, class = UnitClass.Tank, unit = "t20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234"},
			{priority = 0.9, class = UnitClass.Tank, unit = "t26"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3_pax"}
			}
		}
	},
	{--purchase 7
		Repeat = 1,
		Units = {
			["eng"] = {--Commonwealth
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(eng)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_eng"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(eng)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(eng)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(eng)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(eng)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "crusaderaa1"},
				{priority = 1.0, class = UnitClass.Tank, unit = "mk6"},
				{priority = 1.0, class = UnitClass.Tank, unit = "cromwell_mk_vii"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m4a4"},
				{priority = 1.0, class = UnitClass.Tank, unit = "cometa34"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "archer"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "achilles"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "m4a4_firefly"},
				{priority = 1.0, min_income = 3.0, min_team = 3, class = UnitClass.HeavyTank, unit = "centurion"},
				{priority = 0.5, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "m7_eng"}
			},
			["ger"] = {--Germany
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_ger"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(ger)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(ger)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(ger)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(ger)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "ostwind"},
				{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz4g"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz4h"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "stug3g"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "jagdpanzer_iv"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "pz6e"},
				{priority = 1.0, min_income = 3.0, min_team = 3, class = UnitClass.HeavyTank, unit = "pz5g"},
				{priority = 0.5, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "hummel"}
			},
			["ger2"] = {--Ostfront Veteranen
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(ger2)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_ost"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(ger2)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(ger2)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(ger2)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(ger2)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "ostwind_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz3f_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz4g_ger2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "pz4h_ger2"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "hetzer_ger2"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "nashorn_ger2"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "pz6e_ger2"},
				{priority = 1.0, min_income = 3.0, min_team = 3, class = UnitClass.HeavyTank, unit = "pz5g_ger2"},
				{priority = 0.5, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "sdkfz138_1"}
			},
			["usa"] = {--USA
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(usa)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_usa"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(usa)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(usa)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(usa)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(usa)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "m19"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m24"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m18"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m4a3_75"},
				{priority = 1.0, class = UnitClass.Tank, unit = "m4a3e8"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "m10wolverine"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "m36"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "m4a3e2_jumbo"},
				{priority = 1.0, min_income = 3.0, min_team = 3, class = UnitClass.HeavyTank, unit = "m26_pershing"},
				{priority = 0.5, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "m12gmc"}
			},
			["rus"] = {--Soviet Union
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(rus)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_rus"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(rus)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(rus)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(rus)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(rus)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "zsu37"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_0"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_2"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_1"},
				{priority = 1.0, class = UnitClass.Tank, unit = "t34_3"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "su76"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "su85"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "kv85"},
				{priority = 1.0, min_income = 3.0, min_team = 3, class = UnitClass.HeavyTank, unit = "is1"},
				{priority = 0.5, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "isu152"}
			},
			["jap"] = {--Japan
				{priority = 3.0, class = UnitClass.Infantry, unit = "smgs(jap)"},
				{priority = 3.0, class = UnitClass.Infantry, unit = "riflemans(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers1(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers3(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "home_guards(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "mgs2(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "elites(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "stormtroopers(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "storm_mech_jap"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "flamers(jap)"},
				{priority = 1.0, class = UnitClass.Infantry, unit = "snipers(jap)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "bazookers(jap)"},
				{priority = 1.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(jap)"},
				{priority = 1.0, class = UnitClass.AATank, unit = "isuzutx40_aa"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-ha57"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-ha47"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-he"},
				{priority = 1.0, class = UnitClass.Tank, unit = "chi-nu"},
				{priority = 1.0, class = UnitClass.ATTank, unit = "ho-ni1"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "ho-ri"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "chi-to"},
				{priority = 1.0, min_income = 3.0, min_team = 3, class = UnitClass.HeavyTank, unit = "chi-ri"},
				{priority = 0.5, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "ho-ro"}
			},
			["tra"] = {--Tractor
				{priority = 3.0, class = UnitClass.Vehicle, unit = "universal"}
			},
			["rob"] = {--Roboti
			{priority = 1.0, class = UnitClass.Infantry, unit = "homs400(rob)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "home_guard(rob)"},
			{priority = 1.5, class = UnitClass.Infantry, unit = "homs(rob)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "willysat"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m8"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3"}
			},
			["ukr"] = {--Ukraresh
			{priority = 0.5, class = UnitClass.Infantry, unit = "zelyn(ukr)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "macarons(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "shews(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "obors(ukr)"},
			{priority = 1.1, class = UnitClass.Infantry, unit = "banderas(ukr)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "r12"},
			{priority = 0.5, class = UnitClass.Tank, unit = "sdkfz251_1"},
			{priority = 0.5, class = UnitClass.Tank, unit = "pz1b"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz2l"},
			{priority = 0.9, class = UnitClass.Tank, unit = "pz3_ukr"},
			{priority = 1.0, class = UnitClass.Tank, unit = "is2"}
			},
			["pax"] = {--Paxom
			{priority = 0.5, class = UnitClass.Infantry, unit = "paxoms(pax)"},
			{priority = 1.3, class = UnitClass.Infantry, unit = "tesass(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "malkovs(pax)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "pods(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "kats(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "babkas(pax)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "m72"},
			{priority = 0.5, class = UnitClass.Tank, unit = "m3"},
			{priority = 0.5, class = UnitClass.Tank, unit = "t20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234"},
			{priority = 0.9, class = UnitClass.Tank, unit = "t26"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3_pax"}
			}
		}
	},
	{--purchase 8
		Repeat = 0, --infinite
		Units = {
			["eng"] = {--Commonwealth
				{priority = 3.0, min_income = 0, class = UnitClass.Infantry, unit = "smgs(eng)"},
				{priority = 3.0, min_income = 0, class = UnitClass.Infantry, unit = "riflemans(eng)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "stormtroopers1(eng)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "stormtroopers3(eng)"},
				{priority = 1.0, min_income = 0, class = UnitClass.Infantry, unit = "home_guards(eng)"},
				{priority = 1.0, min_income = 0, class = UnitClass.Infantry, unit = "mgs2(eng)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "elites(eng)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "stormtroopers(eng)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "storm_mech_eng"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "flamers(eng)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "snipers(eng)"},
				{priority = 1.0, min_income = 0, class = UnitClass.ATInfantry, unit = "bazookers(eng)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(eng)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.AATank, unit = "crusaderaa1"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Tank, unit = "mk6"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Tank, unit = "cromwell_mk_vii"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.Tank, unit = "m4a4"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.Tank, unit = "cometa34"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.ATTank, unit = "archer"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "achilles"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "m4a4_firefly"},
				{priority = 1.0, min_income = 3.0, min_team = 3, class = UnitClass.HeavyTank, unit = "centurion"},
				{priority = 1.0, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "m7_eng"}
			},
			["ger"] = {--Germany
				{priority = 3.0, min_income = 0, class = UnitClass.Infantry, unit = "smgs(ger)"},
				{priority = 3.0, min_income = 0, class = UnitClass.Infantry, unit = "riflemans(ger)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "stormtroopers1(ger)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "stormtroopers3(ger)"},
				{priority = 1.0, min_income = 0, class = UnitClass.Infantry, unit = "home_guards(ger)"},
				{priority = 1.0, min_income = 0, class = UnitClass.Infantry, unit = "mgs2(ger)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "elites(ger)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "stormtroopers(ger)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "storm_mech_ger"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "flamers(ger)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "snipers(ger)"},
				{priority = 1.0, min_income = 0, class = UnitClass.ATInfantry, unit = "bazookers(ger)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(ger)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.AATank, unit = "ostwind"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Tank, unit = "sdkfz234"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Tank, unit = "pz3"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.Tank, unit = "pz4g"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.Tank, unit = "pz4h"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.ATTank, unit = "stug3g"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "jagdpanzer_iv"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "pz6e"},
				{priority = 1.0, min_income = 3.0, min_team = 3, class = UnitClass.HeavyTank, unit = "pz5g"},
				{priority = 1.0, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "sdkfz4"}
			},
			["ger2"] = {--Ostfront Veteranen
				{priority = 3.0, min_income = 0, class = UnitClass.Infantry, unit = "smgs(ger2)"},
				{priority = 3.0, min_income = 0, class = UnitClass.Infantry, unit = "riflemans(ger2)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "stormtroopers1(ger2)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "stormtroopers3(ger2)"},
				{priority = 1.0, min_income = 0, class = UnitClass.Infantry, unit = "home_guards(ger2)"},
				{priority = 1.0, min_income = 0, class = UnitClass.Infantry, unit = "mgs2(ger2)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "elites(ger2)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "stormtroopers(ger2)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "storm_mech_ost"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "flamers(ger2)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "snipers(ger2)"},
				{priority = 1.0, min_income = 0, class = UnitClass.ATInfantry, unit = "bazookers(ger2)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(ger2)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.AATank, unit = "ostwind_ger2"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Tank, unit = "sdkfz234_ger2"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Tank, unit = "pz3f_ger2"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.Tank, unit = "pz4g_ger2"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.Tank, unit = "pz4h_ger2"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.ATTank, unit = "hetzer_ger2"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "nashorn_ger2"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "pz6e_ger2"},
				{priority = 1.0, min_income = 3.0, min_team = 3, class = UnitClass.HeavyTank, unit = "pz5g_ger2"},
				{priority = 1.0, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "sdkfz251_1_stuka"}
			},
			["usa"] = {--USA
				{priority = 3.0, min_income = 0, class = UnitClass.Infantry, unit = "smgs(usa)"},
				{priority = 3.0, min_income = 0, class = UnitClass.Infantry, unit = "riflemans(usa)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "stormtroopers1(usa)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "stormtroopers3(usa)"},
				{priority = 1.0, min_income = 0, class = UnitClass.Infantry, unit = "home_guards(usa)"},
				{priority = 1.0, min_income = 0, class = UnitClass.Infantry, unit = "mgs2(usa)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "elites(usa)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "stormtroopers(usa)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "storm_mech_usa"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "flamers(usa)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "snipers(usa)"},
				{priority = 1.0, min_income = 0, class = UnitClass.ATInfantry, unit = "bazookers(usa)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(usa)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.AATank, unit = "m19"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Tank, unit = "m24"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Tank, unit = "m18"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.Tank, unit = "m4a3_75"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.Tank, unit = "m4a3e8"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.ATTank, unit = "m10wolverine"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "m36"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "m4a3e2_jumbo"},
				{priority = 1.0, min_income = 3.0, min_team = 3, class = UnitClass.HeavyTank, unit = "m26_pershing"},
				{priority = 1.0, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "m4a3c"}
			},
			["rus"] = {--Soviet Union
				{priority = 3.0, min_income = 0, class = UnitClass.Infantry, unit = "smgs(rus)"},
				{priority = 3.0, min_income = 0, class = UnitClass.Infantry, unit = "riflemans(rus)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "stormtroopers1(rus)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "stormtroopers3(rus)"},
				{priority = 1.0, min_income = 0, class = UnitClass.Infantry, unit = "home_guards(rus)"},
				{priority = 1.0, min_income = 0, class = UnitClass.Infantry, unit = "mgs2(rus)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "elites(rus)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "stormtroopers(rus)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "storm_mech_rus"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "flamers(rus)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "snipers(rus)"},
				{priority = 1.0, min_income = 0, class = UnitClass.ATInfantry, unit = "bazookers(rus)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(rus)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.AATank, unit = "zsu37"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Tank, unit = "t34_0"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Tank, unit = "t34_2"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.Tank, unit = "t34_1"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.Tank, unit = "t34_3"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.ATTank, unit = "su76"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "su85"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "kv85"},
				{priority = 1.0, min_income = 3.0, min_team = 3, class = UnitClass.HeavyTank, unit = "is1"},
				{priority = 1.0, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "bm13"}
			},
			["jap"] = {--Japan
				{priority = 3.0, min_income = 0, class = UnitClass.Infantry, unit = "smgs(jap)"},
				{priority = 3.0, min_income = 0, class = UnitClass.Infantry, unit = "riflemans(jap)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "stormtroopers1(jap)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "stormtroopers3(jap)"},
				{priority = 1.0, min_income = 0, class = UnitClass.Infantry, unit = "home_guards(jap)"},
				{priority = 1.0, min_income = 0, class = UnitClass.Infantry, unit = "mgs2(jap)"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Infantry, unit = "elites(jap)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "stormtroopers(jap)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "storm_mech_jap"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "flamers(jap)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Infantry, unit = "snipers(jap)"},
				{priority = 1.0, min_income = 0, class = UnitClass.ATInfantry, unit = "bazookers(jap)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.ATInfantry, unit = "stormtroopers2(jap)"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.AATank, unit = "isuzutx40_aa"},
				{priority = 1.0, min_income = 1.5, class = UnitClass.Tank, unit = "chi-ha57"},
				{priority = 1.0, min_income = 2.0, class = UnitClass.Tank, unit = "chi-ha47"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.Tank, unit = "chi-he"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.Tank, unit = "chi-nu"},
				{priority = 1.0, min_income = 2.5, class = UnitClass.ATTank, unit = "ho-ni1"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.ATTank, unit = "ho-ri"},
				{priority = 1.0, min_income = 3.0, min_team = 2, class = UnitClass.HeavyTank, unit = "chi-to"},
				{priority = 1.0, min_income = 3.0, min_team = 3, class = UnitClass.HeavyTank, unit = "chi-ri"},
				{priority = 1.0, min_income = 3.5, min_team = 4, class = UnitClass.ArtilleryTank, unit = "ha-to"}
			},
			["tra"] = {--Tractor
				{priority = 3.0, class = UnitClass.Vehicle, unit = "universal"}
			},
			["rob"] = {--Roboti
			{priority = 1.0, class = UnitClass.Infantry, unit = "homs400(rob)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "home_guard(rob)"},
			{priority = 1.5, class = UnitClass.Infantry, unit = "homs(rob)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "willysat"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "m8"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3"}
			},
			["ukr"] = {--Ukraresh
			{priority = 0.5, class = UnitClass.Infantry, unit = "zelyn(ukr)"},
			{priority = 2.0, class = UnitClass.Infantry, unit = "macarons(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "shews(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "obors(ukr)"},
			{priority = 1.1, class = UnitClass.Infantry, unit = "banderas(ukr)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "r12"},
			{priority = 0.5, class = UnitClass.Tank, unit = "sdkfz251_1"},
			{priority = 0.5, class = UnitClass.Tank, unit = "pz1b"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz2l"},
			{priority = 0.9, class = UnitClass.Tank, unit = "pz3_ukr"},
			{priority = 1.0, class = UnitClass.Tank, unit = "is2"}
			},
			["pax"] = {--Paxom
			{priority = 0.5, class = UnitClass.Infantry, unit = "paxoms(pax)"},
			{priority = 1.3, class = UnitClass.Infantry, unit = "tesass(ukr)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "malkovs(pax)"},
			{priority = 0.8, class = UnitClass.Infantry, unit = "farcs(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "pods(pax)"},
			{priority = 1.0, class = UnitClass.Infantry, unit = "shews(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "kats(pax)"},
			{priority = 0.7, class = UnitClass.Infantry, unit = "babkas(pax)"},
			{priority = 0.5, class = UnitClass.Vehicle, unit = "m72"},
			{priority = 0.5, class = UnitClass.Tank, unit = "m3"},
			{priority = 0.5, class = UnitClass.Tank, unit = "t20"},
			{priority = 1.0, class = UnitClass.Tank, unit = "sdkfz234"},
			{priority = 0.9, class = UnitClass.Tank, unit = "t26"},
			{priority = 1.0, class = UnitClass.Tank, unit = "pz3_pax"}
			}
		}
	}
}